import type { Metadata } from "next";
import { Providers } from "./components/providers";

export const metadata: Metadata = {
  title: "Neo pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
